fix: gh cleanup-notifications can be run from any directory
Without this, when run outside of the project directory, an error was
raised because `index.js` was specified incorrectly:

```
$ gh cleanup-notifications --verbose --dry-run | ts
node:internal/modules/cjs/loader:1222
  throw err;
  ^

Error: Cannot find module '/Users/andrewendt/index.js
```